const mark = `<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M24 4 8 29M32 11 16 36" fill="none" stroke="currentColor" stroke-width="6"/><path d="m26 4 8 0-3 8M14 36H6l3-8" fill="currentColor"/></svg>`;
const arrow = `<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.7"/></svg>`;
export function mountUI() {
  document.querySelector<HTMLDivElement>("#app")!.innerHTML = `
    <div id="stage"><canvas id="game-canvas" aria-label="Three-dimensional portal puzzle chamber"></canvas><div class="scene-vignette"></div></div>
    <header class="topbar"><a class="wordmark" href="#" aria-label="Parallax home">${mark}<span>PARALLAX<small>SPATIAL RESEARCH DIVISION</small></span></a><div class="header-center"><span class="status-dot"></span> SYSTEM ONLINE <span class="header-separator">/</span> EXPERIMENT 001–003</div><div class="header-actions"><button id="help-button" class="text-button">How to play <span>↗</span></button><button id="sound-button" class="icon-button" aria-label="Mute sound" title="Toggle sound"><svg viewBox="0 0 24 24" fill="none"><path d="m11 5-5 4H3v6h3l5 4V5Zm4 3c3 2 3 6 0 8m3-11c5 4 5 10 0 14" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg></button><button id="fullscreen-button" class="icon-button" aria-label="Enter fullscreen" title="Fullscreen"><svg viewBox="0 0 24 24" fill="none"><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5" stroke="currentColor" stroke-width="1.5"/></svg></button></div></header>
    <main id="menu" class="menu"><div class="eyebrow"><span class="tiny-cross">+</span> AN EXERCISE IN THINKING DIFFERENTLY</div><h1>Distance is<br> an <em>illusion.</em></h1><p class="intro">Two portals. A different perspective.<br> Find your way through the impossible.</p><div class="chamber-picker"><div class="section-label"><span>SELECT TEST CHAMBER</span><span id="progress-label">00 / 03 COMPLETE</span></div><div id="chamber-list"></div></div><button id="start-button" class="primary-button"><span>Enter chamber</span>${arrow}</button><div class="menu-note"><span class="status-dot"></span> NO DOWNLOAD. JUST A LITTLE CURIOSITY.</div><div class="experiment-caption"><span class="outline-portal blue"></span><span class="outline-portal orange"></span><p>A Portal-inspired experiment.<br>Original chambers. Familiar possibilities.</p></div></main>
    <div id="scene-label" class="scene-label"><span class="live-dot"></span> LIVE CHAMBER PREVIEW <span class="scene-label-divider"></span> <span id="preview-code">01</span></div>
    <div id="scene-caption" class="scene-caption"><div class="coordinate-label">PARALLAX RESEARCH FACILITY <span>SECTOR A</span></div><div class="scene-name"><span id="preview-name">The other side</span><span id="preview-number">01</span></div><div class="scene-caption-bottom"><span>NON-EUCLIDEAN TESTING INITIATIVE</span><span>EST. 1987</span></div></div>
    <footer id="menu-footer"><span class="footer-title">A NEW WAY<br>THROUGH.</span><div class="control-tip"><span class="key-cluster"><kbd>W</kbd><span><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span></span><span>Move<br><small>Find your perspective</small></span></div><div class="control-tip"><span class="mouse-icon"><i></i></span><span>Place portals<br><small>Left click · Right click</small></span></div><div class="control-tip"><kbd class="large-key">E</kbd><span>Interact<br><small>Pick up · Put down</small></span></div><div class="footer-end">THINK BEYOND<br>THE STRAIGHT LINE ${arrow}</div></footer>
    <div id="hud" hidden><div class="hud-mission"><span id="hud-code">CHAMBER 01</span><h2 id="hud-title"></h2><p id="hud-objective"></p></div><div id="crosshair"><i></i><i></i><span></span></div><div id="interaction-prompt"></div><div class="hud-bottom"><div class="portal-status"><div id="portal-blue"><span class="outline-portal blue"></span><span>01 <small>BLUE</small></span></div><span class="portal-link">⟷</span><div id="portal-orange"><span class="outline-portal orange"></span><span>02 <small>ORANGE</small></span></div></div><div class="hud-shortcuts"><span><kbd>WASD</kbd> Move</span><span><kbd>SPACE</kbd> Jump</span><span><kbd>E</kbd> Interact</span><span><kbd>R</kbd> Reset</span><span><kbd>ESC</kbd> Pause</span></div><button id="hint-button" class="hud-hint">Need a hint? <kbd>H</kbd></button></div><div id="timer">00:00</div><button id="pause-button" class="pause-button" aria-label="Pause game">Ⅱ</button><div id="mobile-controls"><div class="dpad"><button data-move="forward" aria-label="Move forward">↑</button><button data-move="left" aria-label="Move left">←</button><button data-move="back" aria-label="Move backward">↓</button><button data-move="right" aria-label="Move right">→</button></div><div class="touch-actions"><button id="touch-blue">BLUE</button><button id="touch-orange">ORANGE</button><button id="touch-interact">PICK UP</button><button id="touch-jump">JUMP</button></div><span class="drag-hint">Drag to look</span></div></div>
    <div id="toast" role="status"></div><div id="flash"></div>
    <dialog id="help-dialog"><button class="dialog-close" aria-label="Close instructions">×</button><div class="eyebrow">SUBJECT ORIENTATION</div><h2>Space is negotiable.</h2><p>Make a blue portal and an orange portal on the pale framed wall panels. Step into one. Come out of the other.</p><div class="help-portal-diagram"><span class="outline-portal blue"></span><span>YOU →</span><span class="dashed-line"></span><span>→ YOU</span><span class="outline-portal orange"></span></div><div class="help-grid"><div><kbd>W A S D</kbd><span>Move through the chamber</span></div><div><kbd>MOUSE</kbd><span>Look around</span></div><div><kbd>LEFT / 1</kbd><span>Place the blue portal</span></div><div><kbd>RIGHT / 2</kbd><span>Place the orange portal</span></div><div><kbd>SPACE</kbd><span>Jump</span></div><div><kbd>E</kbd><span>Pick up or put down a cube</span></div><div><kbd>R</kbd><span>Restart the chamber</span></div><div><kbd>ESC</kbd><span>Pause and release the mouse</span></div></div><p class="help-note">Place cubes on circular pressure pads to open the exit. Gaps are wider than you can jump. On touchscreens, drag to look and use the on-screen controls. If mouse capture is unavailable, drag to look or use the arrow keys.</p><button id="help-done" class="primary-button"><span>Let’s bend some space</span>${arrow}</button></dialog>
    <dialog id="pause-dialog"><div class="eyebrow">EXPERIMENT ON HOLD</div><h2>A moment<br>of perspective.</h2><p>Your chamber is right where you left it.</p><button id="resume-button" class="primary-button"><span>Resume experiment</span>${arrow}</button><button id="restart-button" class="secondary-button">Restart chamber</button><button id="menu-button" class="text-button dialog-menu">Return to chamber selection</button></dialog>
    <dialog id="complete-dialog"><div class="eyebrow">HYPOTHESIS CONFIRMED</div><div class="complete-symbol">✓</div><h2 id="complete-title">Beautifully<br>unexpected.</h2><p id="complete-message"></p><div class="result-stats"><div><span id="result-time"></span><small>ELAPSED TIME</small></div><div><span id="result-portals"></span><small>PORTAL TRAVERSALS</small></div></div><button id="next-button" class="primary-button"><span>Next chamber</span>${arrow}</button><button id="complete-menu" class="text-button dialog-menu">Return to chamber selection</button></dialog>
    <div id="webgl-error" hidden><h2>This experiment needs WebGL.</h2><p>Enable hardware acceleration in your browser, then reload to enter the chamber.</p></div>`;
}
